from __future__ import annotations

import json
import shutil
import subprocess
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

import pytest
from jinja2 import Environment, FileSystemLoader

from ..conftest import RouteRule, SipUserFixture

_TEMPLATES_DIR = Path(__file__).parent / "templates"
_BACKEND_TIMEOUT_S = 5
_PCAP_PATHS = {
    "g711a": Path(__file__).parent / "g711a.pcap",
    # g711a.pcap re-encoded to real G.722 (same SSRC/seq/timestamps/packet
    # sizes) - see README.md for the regeneration command. Used by the
    # transcode scenario, which needs the callee to actually send G.722 for
    # MediaBridge's decode/resample/encode path to be meaningfully exercised.
    "g722": Path(__file__).parent / "g722.pcap",
    # PCMU audio with one RFC 4733 telephone-event digit under PT 101 —
    # generated by gen_dtmf_pcap.py (see README.md). Played by the caller
    # leg in the dtmf_pt_rewrite scenario; the callee negotiates DTMF under
    # a different PT (100), forcing MediaBridge's DTMF-PT-rewrite path.
    "dtmf": Path(__file__).parent / "dtmf.pcap",
}


@dataclass(frozen=True)
class Ports:
    local_ip: str = "127.0.0.1"
    sbc_port: int = 5060
    callee_port: int = 5061
    caller_port: int = 5062
    register_port: int = 5063
    callee_media_port: int = 6006
    caller_media_port: int = 6002


@pytest.fixture(scope="session")
def ports() -> Ports:
    return Ports()


@pytest.fixture(scope="session")
def sip_port(ports: Ports) -> int:
    return ports.sbc_port


def pytest_addoption(parser: pytest.Parser) -> None:
    parser.addoption(
        "--live-backend-url",
        default="http://127.0.0.1:3001",
        help=(
            "Base URL of the real Backend a --live-engine SbcEngine is connected "
            "to (see settings.toml's [control_plane].ws_url on that engine). Used "
            "only to provision this suite's registered_user/other_registered_user "
            "through the Backend's REST API for the register scenarios -- ignored "
            "otherwise."
        ),
    )


@pytest.fixture(scope="session")
def registered_user() -> SipUserFixture:
    # A domain distinct from anything the call scenarios route through
    # (which all use bare IP:port destinations), so the registrar's local-
    # domain check never interacts with them.
    return SipUserFixture(username="alice", realm="sbc-test.local", password="secret123")


@pytest.fixture(scope="session")
def other_registered_user(registered_user: SipUserFixture) -> SipUserFixture:
    # A second, unrelated account in the same realm as registered_user --
    # only exists so a test can authenticate as one user and try to bind
    # this one's AOR instead (see test_b2bua_register_wrong_aor_rejected).
    return SipUserFixture(username="bob", realm=registered_user.realm, password="hunter2")


@pytest.fixture(scope="session")
def sip_users(registered_user: SipUserFixture, other_registered_user: SipUserFixture) -> list[SipUserFixture]:
    return [registered_user, other_registered_user]


@pytest.fixture(scope="session")
def initial_routes(ports: Ports) -> dict[int, RouteRule]:
    # SIPp's [service] macro defaults to the literal "service", so this is
    # the exact request-URI the caller scenario will send.
    return {
        2: RouteRule(
            uri=f"sip:service@{ports.local_ip}:{ports.sbc_port}",
            sip_address=ports.local_ip,
            port=ports.callee_port,
        ),
    }


@pytest.fixture(scope="session")
def sipp_binary() -> Path:
    resolved = shutil.which("sipp")
    if resolved is None:
        pytest.skip("sipp is not installed or not on PATH")

    sipp_path = Path(resolved).resolve()
    caps = subprocess.run(["getcap", str(sipp_path)], capture_output=True, text=True, check=False).stdout
    if "cap_net_raw" not in caps:
        pytest.skip(
            "sipp needs CAP_NET_RAW to replay pcap audio; run once: "
            f"sudo setcap cap_net_raw+ep {sipp_path}"
        )
    return sipp_path


@pytest.fixture(scope="session")
def _jinja_env() -> Environment:
    return Environment(loader=FileSystemLoader(_TEMPLATES_DIR), keep_trailing_newline=True)


@pytest.fixture
def render_scenario(_jinja_env: Environment, tmp_path: Path) -> Callable[..., Path]:
    def _render(template_name: str, *, pcap: str = "g711a", **params: object) -> Path:
        rendered = _jinja_env.get_template(template_name).render(pcap_path=_PCAP_PATHS[pcap], **params)
        out_path = tmp_path / template_name.removesuffix(".j2")
        out_path.write_text(rendered)
        return out_path

    return _render


def _run_sipp(sipp_binary: Path, scenario: Path, target: str | None, local_ip: str, local_port: int, media_port: int):
    args = [str(sipp_binary), "-sf", str(scenario)]
    if target is not None:
        args.append(target)
    args += ["-i", local_ip, "-p", str(local_port), "-mp", str(media_port), "-m", "1", "-nostdin"]
    return subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)


def _stop(process: subprocess.Popen[str]) -> None:
    if process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait()


@pytest.fixture
def run_sipp_pair(sipp_binary: Path, sbc_engine, ports: Ports) -> Callable[[Path, Path], None]:
    def _run(caller_scenario: Path, callee_scenario: Path) -> None:
        callee = _run_sipp(
            sipp_binary, callee_scenario, None, ports.local_ip, ports.callee_port, ports.callee_media_port
        )
        # Give the callee time to bind before the caller dials it; matches
        # the previous run_test.py orchestration.
        time.sleep(1)
        if callee.poll() is not None:
            output, _ = callee.communicate()
            pytest.fail(f"callee sipp exited early ({callee.returncode}):\n{output}")

        caller = _run_sipp(
            sipp_binary,
            caller_scenario,
            f"{ports.local_ip}:{ports.sbc_port}",
            ports.local_ip,
            ports.caller_port,
            ports.caller_media_port,
        )
        try:
            caller_output, _ = caller.communicate(timeout=60)
            callee_output, _ = callee.communicate(timeout=60)
        finally:
            _stop(caller)
            _stop(callee)

        if caller.returncode != 0:
            pytest.fail(f"caller sipp failed ({caller.returncode}):\n{caller_output}")
        if callee.returncode != 0:
            pytest.fail(f"callee sipp failed ({callee.returncode}):\n{callee_output}")

    return _run


def _backend_call(base_url: str, method: str, path: str, body: dict | None = None) -> tuple[int, bytes]:
    data = json.dumps(body).encode() if body is not None else None
    headers = {"Content-Type": "application/json"} if data is not None else {}
    request = urllib.request.Request(f"{base_url}{path}", data=data, method=method, headers=headers)
    try:
        with urllib.request.urlopen(request, timeout=_BACKEND_TIMEOUT_S) as response:
            return response.status, response.read()
    except urllib.error.HTTPError as exc:
        return exc.code, exc.read()
    except urllib.error.URLError as exc:
        pytest.fail(f"could not reach Backend at {base_url} ({exc.reason}); is it running?")


def _create_sip_user(base_url: str, user: SipUserFixture) -> int | None:
    status, raw = _backend_call(
        base_url,
        "POST",
        "/api/sip-users",
        {"username": user.username, "realm": user.realm, "password": user.password, "enabled": user.enabled},
    )
    if status == 409:
        return None  # a leftover row from an earlier interrupted --live-engine run
    if status != 201:
        pytest.fail(f"POST /api/sip-users for {user.username}@{user.realm} failed ({status}): {raw.decode()}")
    return json.loads(raw)["data"]["id"]


def _find_sip_user_id(base_url: str, username: str, realm: str) -> int | None:
    status, raw = _backend_call(base_url, "GET", "/api/sip-users")
    if status != 200:
        pytest.fail(f"GET /api/sip-users failed ({status}): {raw.decode()}")
    for row in json.loads(raw)["data"]:
        if row["username"] == username and row["realm"] == realm:
            return row["id"]
    return None


def _delete_sip_user(base_url: str, user_id: int) -> None:
    _backend_call(base_url, "DELETE", f"/api/sip-users/{user_id}")


@pytest.fixture(scope="session")
def _live_registered_users(request, sip_users: list[SipUserFixture]):
    """Provisions this suite's registered_user/other_registered_user for real
    through the Backend's REST API when --live-engine is set -- the register
    scenarios need them to exist for the already-running engine's registrar
    to recognize `sbc-test.local` as a known realm at all (see
    RegistrarActions::local_domain in registrar_actions.cpp), and there's no
    owned engine process left for this suite to seed them into directly.
    Only requested by run_sipp_register, so plain call scenarios never touch
    the real Backend. No-op outside --live-engine."""
    if not request.config.getoption("--live-engine"):
        yield
        return

    base_url = request.config.getoption("--live-backend-url")
    created_ids = []
    for user in sip_users:
        user_id = _create_sip_user(base_url, user)
        if user_id is None:
            existing_id = _find_sip_user_id(base_url, user.username, user.realm)
            if existing_id is not None:
                _delete_sip_user(base_url, existing_id)
            user_id = _create_sip_user(base_url, user)
            if user_id is None:
                pytest.fail(f"could not provision SIP user {user.username}@{user.realm} on the Backend")
        created_ids.append(user_id)

    yield

    for user_id in created_ids:
        _delete_sip_user(base_url, user_id)


@pytest.fixture
def run_sipp_register(
    sipp_binary: Path, sbc_engine, ports: Ports, _live_registered_users
) -> Callable[[Path], None]:
    """A single SIPp instance against the SBC, no callee -- REGISTER never
    reaches a second leg. Each register.xml.j2 render already declares its
    own expected final status (see expected_status), so a clean SIPp exit
    *is* the assertion, exactly like run_sipp_pair."""

    def _run(scenario: Path) -> None:
        process = _run_sipp(
            sipp_binary,
            scenario,
            f"{ports.local_ip}:{ports.sbc_port}",
            ports.local_ip,
            ports.register_port,
            ports.caller_media_port,
        )
        try:
            output, _ = process.communicate(timeout=15)
        finally:
            _stop(process)
        if process.returncode != 0:
            pytest.fail(f"register sipp failed ({process.returncode}):\n{output}")

    return _run
