macro(enable_clang_tidy_globally ENABLE_CLANG_TIDY)
    if(ENABLE_CLANG_TIDY)
        find_program(CLANG_TIDY_EXE NAMES clang-tidy)
        if(CLANG_TIDY_EXE)
            set(CMAKE_CXX_CLANG_TIDY "${CLANG_TIDY_EXE};--config-file=${CMAKE_SOURCE_DIR}/.clang-tidy")
            message(STATUS "Clang-Tidy enabled globally")
        else()
            message(WARNING "Clang-tidy requested, but clang-tidy binary was not found in PATH")
        endif()
    endif()
endmacro()